#' Compute case and deaths trends
#'
#' @param df JHSU CSSE data
#' @param time_unit_extent defaults to 14 days
#'
#' @return tibble
#' @export
get_trends <- function(df,
                       time_unit_extent = 14,
                       omit_past_days = 2,
                       add_ci         = FALSE) {

  ## params
  # don't include latest 2 days as likely data is incomplete
  last_date <- max(df$date, na.rm = TRUE) - omit_past_days
  dates_extent <- c(last_date - (time_unit_extent - 1), last_date)

  ## get trends
  trends_all <- df %>%
    dplyr::group_by(iso_a3) %>%
    tidyr::nest() %>%
    dplyr::mutate(model = map(data, model_trends, dates_extent, add_ci = add_ci)) %>%
    dplyr::select(-data) %>%
    tidyr::unnest(model)

  df %>%
    dplyr::group_by(continent, region, country, iso_a3) %>%
    dplyr::summarise(cases = sum(cases, na.rm = TRUE),
                     deaths = sum(deaths, na.rm = TRUE)) %>%
    dplyr::ungroup() %>%
    dplyr::inner_join(trends_all)
}

#' @noRd
#' @keywords internal
model_trends <- function(x,
                         dates_extent,
                         ma_window = 3,
                         min_sum   = 30,
                         add_ci    = FALSE) {

  # filter data to date range of interest
  xsub <- x %>%
    dplyr::filter(dplyr::between(date, dates_extent[1], dates_extent[2])) %>%
    tidyr::complete(
      date = seq.Date(min(date, na.rm = TRUE), max(date, na.rm = TRUE), by = 1),
      fill = list(cases = NA_real_, deaths = NA_real_)
    )

  cases <- get_trend(xsub, "cases", min_sum, ma_window)
  deaths <- get_trend(xsub, "deaths", min_sum, ma_window)


  if (add_ci == FALSE) {
    tibble::tibble(
      trend_cases        = cases$trend,
      trend_cases_coeff  = cases$coeff,
      trend_deaths       = deaths$trend,
      trend_deaths_coeff = deaths$coeff)
  } else {
    tibble::tibble(
      trend_cases             = cases$trend,
      trend_cases_coeff       = cases$coeff,
      trend_cases_coeff_lwr95 = cases$lwr95,
      trend_cases_coeff_upr95 = cases$upr95,

      trend_deaths             = deaths$trend,
      trend_deaths_coeff       = deaths$coeff,
      trend_deaths_coeff_lwr95 = deaths$lwr95,
      trend_deaths_coeff_upr95 = deaths$upr95)
    }
}

#' @noRd
#' @keywords internal
get_trend <- function(xsub, var, min_sum, ma_window) {
  if (nrow(xsub) > ma_window & sum(xsub[[var]], na.rm = TRUE) > min_sum) {
    # moving average
    xsub$ma <- as.numeric(forecast::ma(xsub[[var]], order = ma_window))
    xsub$ma <- dplyr::na_if(xsub$ma, 0) # PB: I don't think this is good idea, but kept from prev code

    # linear model and confidence intervals
    mdl <- lm(log(ma) ~ date, data = xsub)
    ci80 <- confint(mdl, level = 0.80)
    ci95 <- confint(mdl, level = 0.95)

    # prep output
    tibble::tibble(
      coeff = coefficients(mdl)[[2]],
      lwr80  = ci80[2,1],
      upr80  = ci80[2,2],
      lwr95  = ci95[2,1],
      upr95  = ci95[2,2]
    ) %>%
      dplyr::transmute(
        coeff,
        lwr95,
        upr95,
        trend = case_when(
          lwr95 > 0 ~ "Increasing",
          lwr95 <= 0 & lwr80 > 0 ~ "Likely increasing",
          upr95 < 0 ~ "Decreasing",
          upr95 >= 0 & upr80 < 0  ~ "Likely decreasing",
          lwr80 < 0 & upr80 > 0 ~ "Stable",
          TRUE ~ NA_character_
        )
      )
  } else {
    tibble::tibble(coeff = NA_real_,
                   trend = NA_character_,
                   lwr95 = NA_real_,
                   upr95 = NA_real_)
  }
}



#' Title
#'
#' @param df_trends a dataframe generated by the get_trends() function.
#' Should have the confidence intervals on coeffs to run.
#' @param serie Which serie to use to generate doubling time (cases, deaths, both). Defaults to "both".
#'
#' @return A tibble. The same tibble with additional columns for doubling
#' time estimates and its confidence intervals
#' @export
get_doubling_time <- function(df_trends,
                              serie = "both") {

  if (serie != "deaths") {

    if ("trend_cases_coeff_lwr95" %in% names(df_trends)) {
      df_trends <- df_trends %>%
        dplyr::mutate(doubling_est_cases = log(2) / trend_cases_coeff,
               doubling_lwr_cases = log(2) / trend_cases_coeff_upr95, # Francesco
               doubling_upr_cases = log(2) / trend_cases_coeff_lwr95) %>%
        dplyr::select(continent:trend_cases_coeff_upr95,
               doubling_est_cases, doubling_lwr_cases, doubling_upr_cases,
               everything())
    } else {
      message("No confidence interval provided for coeff for cases;
              please run covidutils::get_trends() with `add_ci = TRUE`")
    }
  }


  if (serie != "cases") {

    if ( "trend_deaths_coeff_lwr95" %in% names(df_trends) ){
      df_trends <- df_trends %>%
        dplyr::mutate( doubling_est_deaths = log(2) / trend_deaths_coeff,
                doubling_lwr_deaths = log(2) / trend_deaths_coeff_upr95,
                doubling_upr_deaths = log(2) / trend_deaths_coeff_lwr95)
    } else {
      message("No confidence interval provided for coeff for deaths;
              please run covidutils::get_trends() with `add_ci = TRUE`")
    }
  }

  return(df_trends)
}

